// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/ebook/PlasmicGlobalVariant__Screen";
import { PlasmicAccueil } from "../components/plasmic/le_body_challenge_ebook/PlasmicAccueil";
import { useRouter } from "next/router";
import Head from "next/head";

function Merci() {
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicAccueil merci={true} title="z" />
      {/* <Head>
        <title key="title">Le BODY CHALLENGE : merci !</title>
      </Head> */}
    </ph.PageParamsProvider>
  );
}

export default Merci;
